// Auth
export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTH_RESULT = 'AUTH_RESULT';

// Question
export const FETCH_QUESTION = 'FETCH_QUESTION';
export const RESET_QUESTION = 'RESET_QUESTION';

// Questions
export const QUESTIONS_START_LISTENING = 'QUESTIONS_START_LISTENING';
export const QUESTIONS_STOP_LISTENING = 'QUESTIONS_STOP_LISTENING';

// MyQuestions
export const MY_QUESTIONS_START_LISTENING = 'MY_QUESTIONS_START_LISTENING';
export const MY_QUESTIONS_STOP_LISTENING = 'MY_QUESTIONS_STOP_LISTENING';

// Answers
export const ANSWERS_START_LISTENING = 'ANSWERS_START_LISTENING';
export const ANSWERS_STOP_LISTENING = 'ANSWERS_STOP_LISTENING';

// AnswerForm
export const SET_ANSWER_TEXT = 'SET_ANSWER_TEXT';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_ERROR = 'SUBMIT_ANSWER_ERROR';
export const RESET_ANSWER_FORM = 'RESET_ANSWER_FORM';

// QuestionForm
export const SET_QUESTION_TEXT = 'SET_QUESTION_TEXT';
export const SUBMIT_QUESTION_SUCCESS = 'SUBMIT_QUESTION_SUCCESS';
export const SUBMIT_QUESTION_ERROR = 'SUBMIT_QUESTION_ERROR';
